- hosts: masters:workers
  become: yes
  remote_user: infra

  tasks:
  - name: Set http/s proxy in /etc/environment
    blockinfile:
      path: /etc/environment
      block: |
        export http_proxy="http://10.0.0.10:3128"
        export https_proxy="http://10.0.0.10:3128"
      state: present
      create: yes

  # - name: Install packages that allow apt to be used over HTTPS
  #   apt:
  #     name: "{{ packages }}"
  #     state: present
  #     update_cache: yes
  #   vars:
  #     packages:
  #     - apt-transport-https
  #     - ca-certificates
  #     - curl
  #     - gnupg-agent
  #     - software-properties-common
 
  - name: modprobe
    command: modprobe br_netfilter

  - name: Add netbridge config ip6
    lineinfile:
      path: /etc/sysctl.d/k8s.conf
      line: 'net.bridge.bridge-nf-call-ip6tables = 1'
      state: present
      create: yes

  - name: Add netbridge config ip4
    lineinfile:
      path: /etc/sysctl.d/k8s.conf
      line: 'net.bridge.bridge-nf-call-iptables = 1'
      state: present
      create: yes

  - name: update sysctl
    command: sysctl --system

#     - name: Add an apt signing key for Docker
#       apt_key:
#         url: https://download.docker.com/linux/ubuntu/gpg
#         state: present

#     - name: Add apt repository for stable version
#       apt_repository:
#         repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
#         state: present

#     - name: Install docker and its dependecies
#       apt: 
#         name: "{{ packages }}"
#         state: present
#         update_cache: yes
#       vars:
#         packages:
#         #- docker-ce 
#         #- docker-ce-cli 
#         - containerd.io
       
#     - name: Remove swapfile from /etc/fstab
#       mount:
#        name: "{{ item }}"
#        fstype: swap
#        state: absent
#       with_items:
#        - swap
#        - none

#     - name: Disable swap
#       command: swapoff -a
#       when: ansible_swaptotal_mb > 0

#     - name: add Kubernetes apt-key
#       apt_key:
#         url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
#         state: present

#     - name: add Kubernetes APT repository
#       apt_repository:
#        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main 
#        state: present
#        filename: 'kubernetes'
      
#     - name: install kubelet
#       apt:
#         name: kubelet=1.20.0-00
#         state: present
#         update_cache: true

#     - name: install kubeadm
#       apt:
#         name: kubeadm=1.20.0-00
#         state: present

# - hosts: masters
#   become: yes
#   tasks:
#     - name: install kubectl
#       apt:
#         name: kubectl=1.20.0-00
#         state: present
#         force: yes
